### ISSUE TITLE
Command not found issue

### ISSUE THREAD

**Issue by bhargavmehta** [classyllama/Wiz#25]
HI,
I installed in ubuntu but it says command not found.
I downloaded the zip.
copied to ~/bin/Wiz
added to ~/.bash_profile

And typed wiz it says command not found

**Comment by erikhansen** [comment]
Wiz is no longer maintained. You should check out n98 Magerun.

Sent from my iPhone

On Jun 17, 2015, at 7:16 AM, Bhargav Mehta <notifications@github.com> wrote:

HI,
I installed in ubuntu but it says command not found.
I downloaded the zip.
copied to ~/bin/Wiz
added to ~/.bash_profile

And typed wiz it says command not found

—
Reply to this email directly or view it on GitHub
<https://github.com/classyllama/Wiz/issues/25>.

**Comment by davidalger** [comment]
@bhargavmehta You copied it to `~/bin/Wiz`, which means you would need to type `Wiz` (not `wiz`, notice the capitalization change). Also for just typing `wiz` to work, you need to make sure that `~/bin` is in your `PATH` var.

As @erikhansen mentioned, wiz is no longer maintained and n98-magerun is a very good alternative (and better tool in general)…unless you're needing one of the things only wiz can do such as dealing with 301 url data. :)
